### ISSUE TITLE
Ansible: From Beginner to Pro

### ISSUE THREAD

**Issue by aristeidis-kypriotis** [StarttechVentures/Library#113]
This book is your concise guide to Ansible, the simple way to automate apps and IT infrastructure. In less than 250 pages, this book takes you from knowing nothing about configuration management to understanding how to use Ansible in a professional setting.

You will learn how to create an Ansible playbook to automatically set up an environment, ready to install an open source project. You’ll extract common tasks into roles that you can reuse across all your projects, and build your infrastructure on top of existing open source roles and modules that are available for you to use. You will learn to build your own modules to perform actions specific to your business. By the end you will create an entire cluster of virtualized machines, all of which have your applications and all their dependencies installed automatically. Finally, you'll test your Ansible playbooks.

Ansible can do as much or as little as you want it to. Ansible: From Beginner to Pro will teach you the key skills you need to be an Ansible professional. You’ll be writing roles and modules and creating entire environments without human intervention in no time at all – add it to your library today.

**What You Will Learn**

- Learn why Ansible is so popular and how to download and install it
- Create a playbook that automatically downloads and installs a popular open source project
- Use open source roles to complete common tasks, and write your own specific to your business
- Extend Ansible by writing your own modules
- Test your infrastructure using Test Kitchen and ServerSpec

**Who This Book Is For**

Developers that currently create development and production environments by hand. If you find yourself running apt-get install regularly, this book is for you. Ansible adds reproducibility and saves you time all at once. Ansible: From Beginner to Pro is great for any developer wanting to enhance their skillset and learn new tools.

**Comment by kapetanos** [comment]
Reserved
